CREATE TABLE file (
file_id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
md5_hash VARCHAR(1024) NOT NULL,
path VARCHAR(1024) NOT NULL,
last_visited_time TIMESTAMP NOT NULL,
UNIQUE (md5_hash, path)
)
