CREATE TABLE file (
file_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
size LONG NOT NULL,
md5_hash VARCHAR(1024) NOT NULL,
path VARCHAR(1024) NOT NULL,
extension VARCHAR(128) NOT NULL,
last_visited_time TIMESTAMP NOT NULL,
UNIQUE (md5_hash, path)
)
